# fly.toml app configuration file generated for face-dancers-2 on 2025-03-20T13:09:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'face-dancers-2'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4096'
  cpu_kind = 'performance'
  cpus = 2
